version: "3.7"

services:
  node-red:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Pacific/Auckland
      - NODE_RED_CREDENTIAL_SECRET=XZ-9qZYA3s!2jpTA
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
